apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: example-spring-boot
  name: springboot-example-[TEAM]
spec:
  rules:
  - host: springboot-example-[TEAM].k8s-techlab.puzzle.ch
    http:
      paths:
      - backend:
          serviceName: example-spring-boot
          servicePort: 80
        path: /
